# Generated by Django 6.0 on 2025-12-17 15:07

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="FortuneHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("birth_date", models.DateField()),
                ("fortune_date", models.DateField(auto_now_add=True)),
                ("star_name", models.CharField(max_length=20)),
                ("star_text", models.TextField()),
                ("star_score", models.IntegerField()),
                ("zodiac_name", models.CharField(max_length=20)),
                ("zodiac_text", models.TextField()),
                ("zodiac_score", models.IntegerField()),
            ],
            options={
                "ordering": ["-fortune_date"],
            },
        ),
    ]
